# Generated by Django 2.2.4 on 2019-08-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Please enter the address of the property you would like assessment', max_length=200)),
                ('insurance_value', models.CharField(help_text='Please enter your monthly insurance value', max_length=200)),
            ],
        ),
    ]
